#!/usr/bin/env node

import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import vm from "node:vm";

const ROOT = process.cwd();
const SHOWME_DIR = path.join(ROOT, "course-site", "assets", "showme");
const CURRICULUM_JS = path.join(ROOT, "course-site", "data", "curriculum.js");
const REGISTRY_JS = path.join(SHOWME_DIR, "_registry.js");
const CATALOG_JSON = path.join(SHOWME_DIR, "_catalog.json");
const CATALOG_JS = path.join(SHOWME_DIR, "_catalog.js");
const SUPPLEMENTS_JSON = path.join(SHOWME_DIR, "_supplements.json");
const SUPPLEMENTS_JS = path.join(SHOWME_DIR, "_supplements.js");
const I18N_CONTENT_JS = path.join(ROOT, "course-site", "data", "i18n-content.js");
const I18N_JS = path.join(ROOT, "course-site", "assets", "i18n.js");
const SUPPORTED_MANUAL_SECTIONS = [
  "getting-started",
  "user-interface",
  "modeling",
  "sculpting-painting",
  "materials-uv",
  "rendering",
  "animation-rigging"
];
const LIBRARY_SECTION_I18N_KEYS = [
  "sectionGettingStartedTitle",
  "sectionGettingStartedCopy",
  "sectionUserInterfaceTitle",
  "sectionUserInterfaceCopy",
  "sectionModelingTitle",
  "sectionModelingCopy",
  "sectionSculptingPaintingTitle",
  "sectionSculptingPaintingCopy",
  "sectionMaterialsUvTitle",
  "sectionMaterialsUvCopy",
  "sectionRenderingTitle",
  "sectionRenderingCopy",
  "sectionAnimationRiggingTitle",
  "sectionAnimationRiggingCopy"
];

function readText(filePath) {
  return fs.readFileSync(filePath, "utf8");
}

function readJson(filePath) {
  return JSON.parse(readText(filePath));
}

function evalScript(filePath, variableName) {
  const source = readText(filePath);
  const context = {};
  vm.createContext(context);
  vm.runInContext(`${source}\nthis.__VALUE__ = ${variableName};`, context, {
    filename: path.basename(filePath)
  });
  return context.__VALUE__;
}

function evalWindowScript(filePath, expression) {
  const source = readText(filePath);
  const context = { window: {} };
  vm.createContext(context);
  vm.runInContext(`${source}\nthis.__VALUE__ = ${expression};`, context, {
    filename: path.basename(filePath)
  });
  return context.__VALUE__;
}

function countKeyOccurrences(source, key) {
  const escaped = key.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const matches = source.match(new RegExp(`${escaped}\\s*:`, "g"));
  return matches ? matches.length : 0;
}

function renderJsConstant(name, data, headerLines) {
  const lines = [];
  headerLines.forEach(function(line) {
    lines.push(`// ${line}`);
  });
  lines.push(`const ${name} = ${JSON.stringify(data, null, 2)};`);
  lines.push(`if (typeof window !== "undefined") window.${name} = ${name};`);
  lines.push(`if (typeof globalThis !== "undefined") globalThis.${name} = ${name};`);
  lines.push("");
  return lines.join("\n");
}

function syncGeneratedFiles() {
  const catalog = readJson(CATALOG_JSON);
  const supplements = readJson(SUPPLEMENTS_JSON);

  const catalogSource = renderJsConstant("SHOWME_CATALOG", catalog, [
    "============================================================",
    "Show Me 카탈로그 데이터",
    "source: _catalog.json",
    "generated by: node tools/showme-tooling.mjs sync",
    "============================================================"
  ]);

  const supplementsSource = renderJsConstant("SHOWME_SUPPLEMENTS", supplements, [
    "============================================================",
    "Show Me 보충 설명 데이터",
    "source: _supplements.json",
    "generated by: node tools/showme-tooling.mjs sync",
    "============================================================"
  ]);

  fs.writeFileSync(CATALOG_JS, catalogSource, "utf8");
  fs.writeFileSync(SUPPLEMENTS_JS, supplementsSource, "utf8");

  console.log("Synced generated data files:");
  console.log(`- ${path.relative(ROOT, CATALOG_JS)}`);
  console.log(`- ${path.relative(ROOT, SUPPLEMENTS_JS)}`);
}

function buildExpectedGeneratedSources() {
  return {
    catalog: renderJsConstant("SHOWME_CATALOG", readJson(CATALOG_JSON), [
      "============================================================",
      "Show Me 카탈로그 데이터",
      "source: _catalog.json",
      "generated by: node tools/showme-tooling.mjs sync",
      "============================================================"
    ]),
    supplements: renderJsConstant("SHOWME_SUPPLEMENTS", readJson(SUPPLEMENTS_JSON), [
      "============================================================",
      "Show Me 보충 설명 데이터",
      "source: _supplements.json",
      "generated by: node tools/showme-tooling.mjs sync",
      "============================================================"
    ])
  };
}

function listHtmlCardIds() {
  return fs.readdirSync(SHOWME_DIR)
    .filter(function(fileName) {
      return fileName.endsWith(".html") && !fileName.startsWith("_");
    })
    .map(function(fileName) {
      return fileName.replace(/\.html$/, "");
    })
    .sort();
}

function getLinkedWidgetIds(curriculum) {
  const linked = new Set();
  curriculum.forEach(function(week) {
    (week.steps || []).forEach(function(step) {
      if (step.showme) {
        const ids = Array.isArray(step.showme) ? step.showme : [step.showme];
        ids.forEach(function(id) { linked.add(id); });
      }

      (step.widgets || []).forEach(function(widget) {
        if (widget && widget.type === "showme" && widget.id) linked.add(widget.id);
      });
    });
  });
  return linked;
}

function mergeCatalogEntry(id, registry, catalog) {
  const base = registry[id] || { label: id, icon: "📖" };
  const category = (catalog.cardOverrides && catalog.cardOverrides[id] && catalog.cardOverrides[id].category)
    || (catalog.categoryMap && catalog.categoryMap[id])
    || "기타";
  const defaults = (catalog.categoryDefaults && catalog.categoryDefaults[category]) || {};
  const overrides = (catalog.cardOverrides && catalog.cardOverrides[id]) || {};
  return Object.assign({
    id,
    category,
    difficulty: "intermediate",
    confusionLabel: "작업 흐름",
    stageLabel: "보조 개념",
    supplementPriority: "medium",
    visualPattern: "comparison",
    prerequisites: [],
    keywords: []
  }, base, defaults, overrides);
}

function getSupplementCoverage(supplements) {
  const covered = new Set();
  Object.values(supplements).forEach(function(item) {
    (item.targets || []).forEach(function(id) {
      covered.add(id);
    });
  });
  return covered;
}

function inspectCardQuality(cardId) {
  const html = readText(path.join(SHOWME_DIR, `${cardId}.html`));
  return {
    hasScenarioNav: html.includes("scenario-nav"),
    hasCauseEffect: html.includes("cause-effect"),
    hasCanvas: html.includes("<canvas"),
    hasQuizBridge: html.includes("showme-quiz-complete"),
    hasTabs: html.includes('data-tab="concept"') && html.includes('data-tab="visual"')
  };
}

function collectCurriculumStrings(value, bucket) {
  if (typeof value === "string") {
    if (/[가-힣]/.test(value)) bucket.add(value);
    return;
  }

  if (Array.isArray(value)) {
    value.forEach(function(item) {
      collectCurriculumStrings(item, bucket);
    });
    return;
  }

  if (!value || typeof value !== "object") return;

  Object.keys(value).forEach(function(key) {
    if (["id", "url", "image", "video", "src", "icon", "status", "keys", "type"].includes(key)) return;
    collectCurriculumStrings(value[key], bucket);
  });
}

function extractHangulSourceStrings(source) {
  const found = new Set();
  const textMatches = source.match(/>([^<]+)</g) || [];
  textMatches.forEach(function(match) {
    const cleaned = match.slice(1, -1).replace(/\s+/g, " ").trim();
    if (/[가-힣]/.test(cleaned)) found.add(cleaned);
  });

  [
    /"([^"\n\r]*[가-힣][^"\n\r]*)"/g,
    /'([^'\n\r]*[가-힣][^'\n\r]*)'/g,
    /`([^`\r]*[가-힣][^`\r]*)`/g
  ].forEach(function(pattern) {
    let match;
    while ((match = pattern.exec(source))) {
      const unquoted = match[1].replace(/\\n/g, " ").replace(/\s+/g, " ").trim();
      if (/[가-힣]/.test(unquoted)) found.add(unquoted);
    }
  });

  return Array.from(found).sort();
}

function runI18nAudit(options) {
  const curriculum = evalScript(CURRICULUM_JS, "CURRICULUM");
  const i18nContent = evalWindowScript(I18N_CONTENT_JS, "window.RPD_I18N_CONTENT");
  const curriculumExact = (i18nContent.curriculum && i18nContent.curriculum.exact) || {};
  const showme = i18nContent.showme || {};
  const showmeCommonExact = (showme.common && showme.common.exact) || {};
  const showmeWidgetExact = showme.widgets || {};

  const curriculumStrings = new Set();
  curriculum.forEach(function(week) {
    collectCurriculumStrings(week, curriculumStrings);
  });

  const curriculumCovered = Array.from(curriculumStrings).filter(function(value) {
    return Object.prototype.hasOwnProperty.call(curriculumExact, value);
  });
  const curriculumMissing = Array.from(curriculumStrings).filter(function(value) {
    return !Object.prototype.hasOwnProperty.call(curriculumExact, value);
  });

  const htmlIds = listHtmlCardIds();
  const showmeReport = htmlIds.map(function(id) {
    const html = readText(path.join(SHOWME_DIR, `${id}.html`));
    const strings = extractHangulSourceStrings(html);
    const exact = showmeWidgetExact[id] && showmeWidgetExact[id].exact ? showmeWidgetExact[id].exact : {};
    const missing = strings.filter(function(value) {
      return !Object.prototype.hasOwnProperty.call(exact, value) &&
        !Object.prototype.hasOwnProperty.call(showmeCommonExact, value);
    });

    return {
      id,
      totalHangulStrings: strings.length,
      uncoveredStrings: missing.length,
      missing
    };
  });

  const report = {
    curriculum: {
      totalHangulStrings: curriculumStrings.size,
      exactCovered: curriculumCovered.length,
      heuristicFallback: curriculumMissing.length,
      missingExamples: curriculumMissing.slice(0, 40)
    },
    showme: {
      widgets: showmeReport.length,
      widgetsWithUncoveredStrings: showmeReport.filter(function(item) {
        return item.uncoveredStrings > 0;
      }).length,
      details: showmeReport
    }
  };

  if (options.json) {
    console.log(JSON.stringify(report, null, 2));
    return;
  }

  console.log("I18n Audit");
  console.log(`- Curriculum hangul strings: ${report.curriculum.totalHangulStrings}`);
  console.log(`- Curriculum exact coverage: ${report.curriculum.exactCovered}`);
  console.log(`- Curriculum heuristic fallback: ${report.curriculum.heuristicFallback}`);
  console.log(`- Show Me widgets: ${report.showme.widgets}`);
  console.log(`- Show Me widgets with uncovered strings: ${report.showme.widgetsWithUncoveredStrings}`);

  if (report.curriculum.missingExamples.length) {
    console.log("\nCurriculum heuristic fallback examples:");
    report.curriculum.missingExamples.forEach(function(item) {
      console.log(`- ${item}`);
    });
  }

  console.log("\nShow Me uncovered string counts:");
  report.showme.details.forEach(function(item) {
    console.log(`- ${item.id}: ${item.uncoveredStrings}`);
  });
}

function runAudit(options) {
  const registry = evalScript(REGISTRY_JS, "SHOWME_REGISTRY");
  const curriculum = evalScript(CURRICULUM_JS, "CURRICULUM");
  const catalog = readJson(CATALOG_JSON);
  const supplements = readJson(SUPPLEMENTS_JSON);
  const htmlCardIds = listHtmlCardIds();
  const registryIds = Object.keys(registry).sort();
  const linkedIds = getLinkedWidgetIds(curriculum);
  const supplementCoverage = getSupplementCoverage(supplements);
  const expectedSources = buildExpectedGeneratedSources();
  const i18nSource = fs.existsSync(I18N_JS) ? readText(I18N_JS) : "";

  const categoryMapIds = Object.keys(catalog.categoryMap || {}).sort();
  const overrideIds = Object.keys(catalog.cardOverrides || {}).sort();
  const manualSectionOrder = Array.isArray(catalog.manualSectionOrder) ? catalog.manualSectionOrder : [];
  const manualSectionMap = catalog.manualSectionMap || {};
  const manualSectionMapIds = Object.keys(manualSectionMap).sort();
  const assignedManualSections = Object.values(manualSectionMap);
  const htmlSet = new Set(htmlCardIds);
  const registrySet = new Set(registryIds);
  const categorySet = new Set(categoryMapIds);
  const linkedSet = new Set(linkedIds);
  const manualSectionSet = new Set(manualSectionOrder);
  const manualSectionMapSet = new Set(manualSectionMapIds);

  const missingHtml = registryIds.filter(function(id) { return !htmlSet.has(id); });
  const unregisteredHtml = htmlCardIds.filter(function(id) { return !registrySet.has(id); });
  const missingCategoryMap = registryIds.filter(function(id) { return !categorySet.has(id); });
  const invalidOverrides = overrideIds.filter(function(id) { return !registrySet.has(id); });
  const emptyManualSectionOrder = manualSectionOrder.length ? [] : ["manualSectionOrder"];
  const duplicateManualSections = manualSectionOrder.filter(function(sectionId, index) {
    return manualSectionOrder.indexOf(sectionId) !== index;
  });
  const invalidManualSectionOrderEntries = manualSectionOrder.filter(function(sectionId) {
    return !SUPPORTED_MANUAL_SECTIONS.includes(sectionId);
  });
  const missingManualSectionMap = registryIds.filter(function(id) { return !manualSectionMapSet.has(id); });
  const invalidManualSectionEntries = manualSectionMapIds.filter(function(id) { return !registrySet.has(id); });
  const unknownManualSections = Array.from(new Set(assignedManualSections)).filter(function(sectionId) {
    return !manualSectionSet.has(sectionId) || !SUPPORTED_MANUAL_SECTIONS.includes(sectionId);
  });
  const unusedManualSections = manualSectionOrder.filter(function(sectionId) {
    return !assignedManualSections.includes(sectionId);
  });
  const missingLibrarySectionI18nKeys = LIBRARY_SECTION_I18N_KEYS.filter(function(key) {
    return countKeyOccurrences(i18nSource, key) < 2;
  });
  const unlinked = registryIds.filter(function(id) { return !linkedSet.has(id); });

  const highPriority = registryIds.filter(function(id) {
    return mergeCatalogEntry(id, registry, catalog).supplementPriority === "high";
  });
  const missingHighPrioritySupplements = highPriority.filter(function(id) {
    return !supplementCoverage.has(id);
  });

  const qualityById = {};
  registryIds.forEach(function(id) {
    if (!htmlSet.has(id)) return;
    qualityById[id] = inspectCardQuality(id);
  });

  const enhancedIds = Object.keys(qualityById).filter(function(id) {
    const quality = qualityById[id];
    return quality.hasScenarioNav && quality.hasCauseEffect && quality.hasCanvas && quality.hasQuizBridge;
  });

  const syncIssues = [];
  if (!fs.existsSync(CATALOG_JS) || readText(CATALOG_JS) !== expectedSources.catalog) {
    syncIssues.push(path.relative(ROOT, CATALOG_JS));
  }
  if (!fs.existsSync(SUPPLEMENTS_JS) || readText(SUPPLEMENTS_JS) !== expectedSources.supplements) {
    syncIssues.push(path.relative(ROOT, SUPPLEMENTS_JS));
  }

  const report = {
    totals: {
      registryEntries: registryIds.length,
      htmlCards: htmlCardIds.length,
      linkedCards: linkedIds.size,
      unlinkedCards: unlinked.length,
      supplementTargets: supplementCoverage.size,
      enhancedCards: enhancedIds.length
    },
    issues: {
      missingHtml,
      unregisteredHtml,
      missingCategoryMap,
      invalidOverrides,
      emptyManualSectionOrder,
      duplicateManualSections,
      invalidManualSectionOrderEntries,
      missingManualSectionMap,
      invalidManualSectionEntries,
      unknownManualSections,
      unusedManualSections,
      missingLibrarySectionI18nKeys,
      unlinked,
      missingHighPrioritySupplements,
      outOfSyncGeneratedFiles: syncIssues
    },
    quality: {
      enhancedIds,
      baselineIds: Object.keys(qualityById).filter(function(id) {
        return !enhancedIds.includes(id);
      })
    }
  };

  if (options.json) {
    console.log(JSON.stringify(report, null, 2));
  } else {
    console.log("ShowMe Audit");
    console.log(`- Registry: ${report.totals.registryEntries}`);
    console.log(`- HTML cards: ${report.totals.htmlCards}`);
    console.log(`- Linked in curriculum: ${report.totals.linkedCards}`);
    console.log(`- Supplement coverage: ${report.totals.supplementTargets}`);
    console.log(`- Enhanced cards: ${report.totals.enhancedCards}`);

    function printList(title, list) {
      console.log(`\n${title}: ${list.length}`);
      if (!list.length) {
        console.log("- none");
        return;
      }
      list.forEach(function(item) {
        console.log(`- ${item}`);
      });
    }

    printList("Missing HTML", report.issues.missingHtml);
    printList("Unregistered HTML", report.issues.unregisteredHtml);
    printList("Missing category mapping", report.issues.missingCategoryMap);
    printList("Invalid catalog overrides", report.issues.invalidOverrides);
    printList("Empty manual section order", report.issues.emptyManualSectionOrder);
    printList("Duplicate manual sections", report.issues.duplicateManualSections);
    printList("Invalid manual section order entries", report.issues.invalidManualSectionOrderEntries);
    printList("Missing manual section mapping", report.issues.missingManualSectionMap);
    printList("Invalid manual section entries", report.issues.invalidManualSectionEntries);
    printList("Unknown manual sections", report.issues.unknownManualSections);
    printList("Unused manual sections", report.issues.unusedManualSections);
    printList("Missing library section i18n keys", report.issues.missingLibrarySectionI18nKeys);
    printList("Unlinked cards", report.issues.unlinked);
    printList("Missing high-priority supplements", report.issues.missingHighPrioritySupplements);
    printList("Out-of-sync generated files", report.issues.outOfSyncGeneratedFiles);
  }

  const hasBlockingIssues = [
    report.issues.missingHtml,
    report.issues.unregisteredHtml,
    report.issues.missingCategoryMap,
    report.issues.invalidOverrides,
    report.issues.emptyManualSectionOrder,
    report.issues.duplicateManualSections,
    report.issues.invalidManualSectionOrderEntries,
    report.issues.missingManualSectionMap,
    report.issues.invalidManualSectionEntries,
    report.issues.unknownManualSections,
    report.issues.missingLibrarySectionI18nKeys,
    report.issues.outOfSyncGeneratedFiles
  ].some(function(list) {
    return list.length > 0;
  });

  if (options.strict && hasBlockingIssues) {
    process.exit(1);
  }
}

function parseArgs(argv) {
  const args = argv.slice(2);
  return {
    command: args[0] || "audit",
    json: args.includes("--json"),
    strict: args.includes("--strict")
  };
}

const options = parseArgs(process.argv);

if (options.command === "sync") {
  syncGeneratedFiles();
} else if (options.command === "audit") {
  runAudit(options);
} else if (options.command === "audit-i18n") {
  runI18nAudit(options);
} else {
  console.error("Usage: node tools/showme-tooling.mjs [sync|audit|audit-i18n] [--json] [--strict]");
  process.exit(1);
}
